name: publish to dev

on:
  push:
    branches:
      - dev
      - feature/CAD-36

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: set the bloody FA Key
        run: scripts/set_the_bloody_fa_pro_key.sh
        env:
          FONTAWESOME_NPM_AUTH_TOKEN: ${{ secrets.FONTAWESOME_PRO_KEY }}
      - name: Install
        uses: CultureHQ/actions-yarn@master
        with:
          args: install
      - name: Build
        uses: CultureHQ/actions-yarn@master
        with:
          args: build
      - name: Deploy
        uses: CultureHQ/actions-yarn@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        with:
          args: s3-deploy './dist/**' --cwd './dist/' --region ap-southeast-2 --bucket mk13-test-bucket
